apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-deploy
  namespace: storage-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: local-demo
  template:
    metadata:
      labels:
        app: local-demo
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo $(date) >> /data/shared.log; sleep 5; done"]
          volumeMounts:
            - name: shared-storage
              mountPath: /data

        - name: multitool
          image: praqma/network-multitool
          command: ["/bin/sh", "-c"]
          args: ["tail -f /data/shared.log"]
          volumeMounts:
            - name: shared-storage
              mountPath: /data
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: pvc-local
