apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-local
  namespace: storage-lab
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
